version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: proje_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: proje_yonetim
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - proje-network

  backend:
    build:
      context: ./backend-clean
    container_name: proje_backend
    ports:
      - "8010:8010"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/proje_yonetim
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
    networks:
      - proje-network

volumes:
  postgres_data:

networks:
  proje-network:

